package resistance.common;

public enum GMPhases {
    
    GM_START_ROUND,
    GM_COLLECT_PREFERENCES,
    GM_TEAM_SELECTION,
    GM_CAST_VOTE,
    GM_COLLECT_MISSION_OUTCOME,
    GM_ASSIGN_MISSION_POINTS,
    GM_END_ROUND,
    GM_GAME_ENDING,
    GM_GAME_ENDED,
    GM_CHECK_GAME_END, INITIAL_STUFF
}
