package resistance.common;

public enum PlayerPhases {
    
    WAIT_NEW_ROUND,
    COMPUTE_PREFERENCES,
    BROADCAST_PREFERENCES,
    RECEIVE_TEAM_FORMATION,
    VOTE_MISSION_OUTCOME,
    UPDATE_CONFIDENCES,
    WAIT_END_ROUND, // ALSO END_GAME
    GAME_ENDED, COLLECT_MISSION_OUTCOME
}
